### ISSUE TITLE
about paw3395 datasheet?

### ISSUE THREAD

**Issue by nine-fox** [ufan/paw3395_pmw3361_breakout#1]
Hi @ufan , this is really cool project! Fantastic! Do you mind me to ask where to locate the paw3395 datasheet in order to develop? Thanks!

nine-fox

**Comment by ufan** [comment]
Sorry for the late reply, you can download it herr: https://cloud.ufan.site:444/index.php/s/fremD5cAtKLczXy
Since I got the datasheet from the retailor, who says it's confidential, the link will expire after 7 days.

**Comment by nine-fox** [comment]
> Sorry for the late reply, you can download it herr: https://cloud.ufan.site:444/index.php/s/fremD5cAtKLczXy Since I got the datasheet from the retailor, who says it's confidential, the link will expire after 7 days.

Got it. Thanks very much! That's really helps

**Comment by Xelus22** [comment]
Hi @ufan is it possible to download the PDF as well please?

**Comment by ufan** [comment]
https://cloud.ufan.site:444/index.php/s/YSoKgsHrGdgg3DB

**Comment by RealKC** [comment]
Hello, would it be possible to make it available to download for me as well?
